version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_N8N_WEBHOOK_URL=http://localhost:5678/webhook/intern-logs
    restart: unless-stopped
    depends_on:
      - database

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - ./data:/data
      - n8n_storage:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_CORS_ORIGIN=*
      - N8N_CORS_METHODS=GET,PUT,POST,DELETE,PATCH,OPTIONS
      - N8N_CORS_HEADERS=Origin,X-Requested-With,Content-Type,Accept,Authorization,Cache-Control
      - N8N_CORS_CREDENTIALS=true
      - N8N_DISABLE_UI=false
      - GENERIC_TIMEZONE=America/Chicago
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - N8N_PUBLIC_API_DISABLED=false
      - N8N_API_KEY_HEADER=X-N8N-API-KEY
      # Database connection for n8n workflows
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=intern_tracker
      - DB_USER=intern_user
      - DB_PASSWORD=intern_password123
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=intern_tracker
      - POSTGRES_USER=intern_user
      - POSTGRES_PASSWORD=intern_password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Optional: Database admin interface
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - ADMINER_DEFAULT_SERVER=database

volumes:
  n8n_storage:
  postgres_data: 